/**
 * Dados demonstrativos do JourneyMatch.
 *
 * Todo o conteúdo é fictício, adulto e respeitoso: nada de linguagem
 * infantilizada, nada de diagnóstico, nada de pontuação de desempenho
 * (documentos 00, 03, 04, 06 e 11).
 *
 * A interface NUNCA importa este arquivo diretamente: ela fala com os
 * repositórios (`repositorios.ts`), que hoje leem daqui e amanhã podem ler
 * de um backend.
 */
import { situacoes } from "@/lib/viva-situacoes";

import type {
  Barrier,
  FeedbackFormat,
  InformationResource,
  MonitoringPreference,
  Need,
  Situation,
  Strategy,
  TrainingResource,
} from "./tipos";

const cenaPorContexto: Record<string, Situation["cena"]> = {
  compras: "lugar",
  mobilidade: "rota",
  saude: "atividade",
  trabalho: "atividade",
  academico: "conteudo",
  indefinido: "etapa",
};

/** 14 situações, todas disponíveis para o perfil único. */
export const situacoesDeMatch: Situation[] = situacoes.map((s) => ({
  id: `situation-${s.id}`,
  categoria: "situation",
  situacaoId: s.id,
  contexto: s.contexto,
  titulo: s.titulo,
  descricao: s.resumo,
  detalhes: `Percurso demonstrativo com ${s.etapas.length} etapas curtas. Você pode mudar, remover ou reordenar tudo depois.`,
  etiqueta: "Situação",
  duracao: s.duracaoAproximada,
  cena: cenaPorContexto[s.contexto] ?? "lugar",
}));

export const necessidades: Need[] = [
  {
    id: "need-ir-e-voltar",
    categoria: "need",
    titulo: "Ir e voltar com tranquilidade",
    descricao: "O trajeto importa tanto quanto o destino.",
    detalhes: "O percurso passa a incluir a volta como etapa própria, com pausa prevista.",
    etiqueta: "Objetivo",
    intensidade: "media",
    cena: "rota",
  },
  {
    id: "need-resolver-uma-coisa",
    categoria: "need",
    titulo: "Resolver só uma coisa hoje",
    descricao: "Uma tarefa, do começo ao fim.",
    detalhes: "As etapas extras ficam marcadas como opcionais.",
    etiqueta: "Objetivo",
    intensidade: "baixa",
    cena: "etapa",
  },
  {
    id: "need-sem-imprevisto",
    categoria: "need",
    titulo: "Saber antes o que vai acontecer",
    descricao: "Previsibilidade em cada passo.",
    detalhes: "Inclui uma etapa de reconhecimento do ambiente e pontos de referência.",
    etiqueta: "Objetivo",
    cena: "conteudo",
  },
  {
    id: "need-comunicar",
    categoria: "need",
    titulo: "Conseguir dizer o que preciso",
    descricao: "Ter o que falar já pronto.",
    detalhes: "Adiciona frases de apoio e a possibilidade de mostrar texto em vez de falar.",
    etiqueta: "Objetivo",
    cena: "atividade",
  },
  {
    id: "need-tempo",
    categoria: "need",
    titulo: "Não ficar mais tempo do que quero",
    descricao: "Hora de sair combinada antes.",
    detalhes: "A etapa de saída ganha horário próprio e não depende de justificativa.",
    etiqueta: "Objetivo",
    cena: "etapa",
  },
  {
    id: "need-energia",
    categoria: "need",
    titulo: "Chegar em casa com energia",
    descricao: "Guardar reserva para depois.",
    detalhes: "Reduz o número de etapas e distribui pausas ao longo do percurso.",
    etiqueta: "Objetivo",
    intensidade: "baixa",
    cena: "registro",
  },
  {
    id: "need-sozinho",
    categoria: "need",
    titulo: "Fazer isso sozinho, do meu jeito",
    descricao: "Autonomia como objetivo explícito.",
    detalhes: "Nenhuma etapa passa a depender de outra pessoa; o apoio fica como alternativa.",
    etiqueta: "Objetivo",
    cena: "perfil",
  },
  {
    id: "need-companhia",
    categoria: "need",
    titulo: "Fazer com alguém de confiança",
    descricao: "Companhia combinada, sem vigilância.",
    detalhes: "Inclui uma etapa de combinar com a pessoa o que ela faz e o que não faz.",
    etiqueta: "Objetivo",
    cena: "alternativa",
  },
  {
    id: "need-ensaiar",
    categoria: "need",
    titulo: "Ensaiar antes de fazer de verdade",
    descricao: "Primeiro a versão de treino.",
    detalhes: "Ativa a etapa de simulação antes da realização.",
    etiqueta: "Objetivo",
    cena: "atividade",
  },
  {
    id: "need-registrar",
    categoria: "need",
    titulo: "Registrar como foi para mim",
    descricao: "Memória própria, sem avaliação.",
    detalhes: "Ativa a etapa de feedback no formato que você escolher.",
    etiqueta: "Objetivo",
    cena: "registro",
  },
];

export const barreiras: Barrier[] = [
  {
    id: "barrier-barulho",
    categoria: "barrier",
    titulo: "Barulho alto ou contínuo",
    etiqueta: "Barreira",
    intensidade: "alta",
    cena: "lugar",
    detalhes: "Ambientes com som constante costumam acelerar o cansaço.",
  },
  {
    id: "barrier-luz",
    categoria: "barrier",
    titulo: "Luz forte ou piscante",
    etiqueta: "Barreira",
    intensidade: "alta",
    cena: "lugar",
    detalhes: "Lâmpadas frias e telas grandes podem incomodar mais que o esperado.",
  },
  {
    id: "barrier-fila",
    categoria: "barrier",
    titulo: "Fila e espera indefinida",
    etiqueta: "Barreira",
    intensidade: "media",
    cena: "etapa",
    detalhes: "Não saber quanto tempo falta pesa mais do que o tempo em si.",
  },
  {
    id: "barrier-multidao",
    categoria: "barrier",
    titulo: "Muita gente ao mesmo tempo",
    etiqueta: "Barreira",
    intensidade: "alta",
    cena: "lugar",
  },
  {
    id: "barrier-improviso",
    categoria: "barrier",
    titulo: "Mudança de plano de última hora",
    etiqueta: "Barreira",
    intensidade: "media",
    cena: "alternativa",
  },
  {
    id: "barrier-falar",
    categoria: "barrier",
    titulo: "Ter que falar com desconhecidos",
    etiqueta: "Barreira",
    intensidade: "media",
    cena: "atividade",
  },
  {
    id: "barrier-telefone",
    categoria: "barrier",
    titulo: "Precisar resolver por telefone",
    etiqueta: "Barreira",
    intensidade: "media",
    cena: "atividade",
  },
  {
    id: "barrier-orientacao",
    categoria: "barrier",
    titulo: "Não achar o caminho no local",
    etiqueta: "Barreira",
    intensidade: "media",
    cena: "rota",
  },
  {
    id: "barrier-transporte",
    categoria: "barrier",
    titulo: "Atraso ou lotação no transporte",
    etiqueta: "Barreira",
    intensidade: "alta",
    cena: "rota",
  },
  {
    id: "barrier-cansaco",
    categoria: "barrier",
    titulo: "Começar o dia já cansado",
    etiqueta: "Barreira",
    intensidade: "baixa",
    cena: "registro",
  },
  {
    id: "barrier-decisao",
    categoria: "barrier",
    titulo: "Muitas decisões seguidas",
    etiqueta: "Barreira",
    intensidade: "media",
    cena: "etapa",
  },
  {
    id: "barrier-documentos",
    categoria: "barrier",
    titulo: "Esquecer documento ou item",
    etiqueta: "Barreira",
    intensidade: "baixa",
    cena: "conteudo",
  },
];

export const estrategias: Strategy[] = [
  {
    id: "strategy-horario-tranquilo",
    categoria: "strategy",
    titulo: "Escolher um horário mais tranquilo",
    descricao: "Fora do pico há menos fila e menos pressa.",
    responde: ["barrier-multidao", "barrier-fila", "barrier-barulho"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "estrategia",
    detalhes: "O percurso sugere um horário alternativo, que você pode ajustar.",
  },
  {
    id: "strategy-fone",
    categoria: "strategy",
    titulo: "Levar fone ou protetor auricular",
    descricao: "Filtra o excesso sem isolar por completo.",
    responde: ["barrier-barulho", "barrier-multidao"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "estrategia",
  },
  {
    id: "strategy-oculos",
    categoria: "strategy",
    titulo: "Usar boné ou óculos escuros",
    descricao: "Reduz a luz direta em ambientes claros.",
    responde: ["barrier-luz"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "estrategia",
  },
  {
    id: "strategy-frases",
    categoria: "strategy",
    titulo: "Levar frases prontas",
    descricao: "Ter o que dizer diminui o esforço na hora.",
    responde: ["barrier-falar", "barrier-telefone"],
    etiqueta: "Estratégia",
    formato: "leitura",
    cena: "estrategia",
  },
  {
    id: "strategy-mostrar-texto",
    categoria: "strategy",
    titulo: "Mostrar um texto em vez de falar",
    descricao: "Escrever também é comunicar.",
    responde: ["barrier-falar"],
    etiqueta: "Estratégia",
    formato: "leitura",
    cena: "estrategia",
  },
  {
    id: "strategy-lista-curta",
    categoria: "strategy",
    titulo: "Levar uma lista curta",
    descricao: "Poucos itens, na ordem do caminho.",
    responde: ["barrier-decisao", "barrier-documentos"],
    etiqueta: "Estratégia",
    formato: "checklist",
    cena: "estrategia",
  },
  {
    id: "strategy-pausas",
    categoria: "strategy",
    titulo: "Combinar pausas comigo mesmo",
    descricao: "Uma pausa curta a cada etapa.",
    responde: ["barrier-cansaco", "barrier-fila"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "estrategia",
  },
  {
    id: "strategy-saida",
    categoria: "strategy",
    titulo: "Saber onde é a saída",
    descricao: "Poder interromper é parte do plano.",
    responde: ["barrier-multidao", "barrier-orientacao"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "estrategia",
  },
  {
    id: "strategy-chegar-antes",
    categoria: "strategy",
    titulo: "Chegar um pouco antes",
    descricao: "Tempo de reconhecer o ambiente sem pressa.",
    responde: ["barrier-improviso", "barrier-orientacao"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "estrategia",
  },
  {
    id: "strategy-referencias",
    categoria: "strategy",
    titulo: "Anotar pontos de referência",
    descricao: "Uma referência antes do destino já avisa.",
    responde: ["barrier-orientacao"],
    etiqueta: "Estratégia",
    formato: "checklist",
    cena: "rota",
  },
  {
    id: "strategy-plano-b",
    categoria: "strategy",
    titulo: "Ter um plano alternativo pronto",
    descricao: "Se algo mudar, já existe outro caminho.",
    responde: ["barrier-improviso", "barrier-transporte"],
    etiqueta: "Estratégia",
    formato: "leitura",
    cena: "alternativa",
  },
  {
    id: "strategy-avisar",
    categoria: "strategy",
    titulo: "Avisar alguém de confiança",
    descricao: "Apoio disponível, sem vigilância.",
    responde: ["barrier-improviso", "barrier-cansaco"],
    etiqueta: "Estratégia",
    formato: "conversa",
    cena: "alternativa",
  },
  {
    id: "strategy-documentos",
    categoria: "strategy",
    titulo: "Fotografar documentos antes de sair",
    descricao: "A cópia fica no celular.",
    responde: ["barrier-documentos"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "conteudo",
  },
  {
    id: "strategy-uma-decisao",
    categoria: "strategy",
    titulo: "Deixar uma decisão por etapa",
    descricao: "Decidir menos vezes cansa menos.",
    responde: ["barrier-decisao"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "etapa",
  },
  {
    id: "strategy-transporte-alternativo",
    categoria: "strategy",
    titulo: "Deixar um segundo meio de transporte à mão",
    descricao: "Se atrasar, existe outra opção.",
    responde: ["barrier-transporte"],
    etiqueta: "Estratégia",
    formato: "pratica",
    cena: "rota",
  },
  {
    id: "strategy-resolver-online",
    categoria: "strategy",
    titulo: "Verificar se dá para resolver à distância",
    descricao: "Às vezes o presencial não é necessário.",
    responde: ["barrier-telefone", "barrier-fila", "barrier-multidao"],
    etiqueta: "Estratégia",
    formato: "leitura",
    cena: "alternativa",
  },
];

export const informacoes: InformationResource[] = [
  {
    id: "info-como-e-o-local",
    categoria: "information",
    titulo: "Como esse tipo de local funciona",
    duracao: "3 min de leitura",
    formato: "leitura",
    etiqueta: "Informação",
    cena: "conteudo",
    detalhes: "Descrição em blocos curtos: entrada, atendimento, espera e saída.",
  },
  {
    id: "info-audio-caminho",
    categoria: "information",
    titulo: "Áudio: o caminho descrito em voz",
    duracao: "4 min",
    formato: "audio",
    etiqueta: "Informação",
    cena: "rota",
  },
  {
    id: "info-video-ambiente",
    categoria: "information",
    titulo: "Vídeo curto do ambiente",
    duracao: "1 min",
    formato: "video",
    etiqueta: "Informação",
    intensidade: "media",
    cena: "lugar",
    midia: { tipo: "video", fonte: "mock://ambiente", descricao: "Vídeo demonstrativo do ambiente." },
  },
  {
    id: "info-frases-uteis",
    categoria: "information",
    titulo: "Frases úteis para pedir informação",
    duracao: "2 min",
    formato: "leitura",
    etiqueta: "Informação",
    cena: "atividade",
  },
  {
    id: "info-documentos",
    categoria: "information",
    titulo: "O que costuma ser pedido de documento",
    duracao: "2 min",
    formato: "checklist",
    etiqueta: "Informação",
    cena: "conteudo",
  },
  {
    id: "info-direitos",
    categoria: "information",
    titulo: "Atendimento prioritário: como pedir",
    duracao: "3 min",
    formato: "leitura",
    etiqueta: "Informação",
    cena: "conteudo",
  },
  {
    id: "info-atraso",
    categoria: "information",
    titulo: "Quando algo atrasa: o que fazer",
    duracao: "3 min",
    formato: "leitura",
    etiqueta: "Informação",
    cena: "alternativa",
  },
  {
    id: "info-sobrecarga",
    categoria: "information",
    titulo: "Sinais de sobrecarga e o que ajuda",
    duracao: "4 min",
    formato: "leitura",
    etiqueta: "Informação",
    cena: "registro",
  },
  {
    id: "info-mapa-referencias",
    categoria: "information",
    titulo: "Mapa por pontos de referência",
    duracao: "2 min",
    formato: "leitura",
    etiqueta: "Informação",
    cena: "rota",
  },
  {
    id: "info-pausas",
    categoria: "information",
    titulo: "Onde encontrar um lugar mais calmo",
    duracao: "2 min",
    formato: "leitura",
    etiqueta: "Informação",
    cena: "lugar",
  },
];

export const treinamentos: TrainingResource[] = [
  {
    id: "training-falar-balcao",
    categoria: "training",
    titulo: "Ensaiar a fala do balcão",
    duracao: "5 min",
    formato: "pratica",
    etiqueta: "Treinamento",
    cena: "atividade",
    detalhes: "Você escolhe as frases e treina no seu tempo, sem correção.",
  },
  {
    id: "training-pedir-ajuda",
    categoria: "training",
    titulo: "Ensaiar pedir uma informação",
    duracao: "4 min",
    formato: "pratica",
    etiqueta: "Treinamento",
    cena: "atividade",
  },
  {
    id: "training-trajeto",
    categoria: "training",
    titulo: "Percorrer o trajeto pelo mapa",
    duracao: "6 min",
    formato: "pratica",
    etiqueta: "Treinamento",
    cena: "rota",
  },
  {
    id: "training-fila",
    categoria: "training",
    titulo: "Simular a espera na fila",
    duracao: "5 min",
    formato: "pratica",
    etiqueta: "Treinamento",
    intensidade: "media",
    cena: "etapa",
  },
  {
    id: "training-respiracao",
    categoria: "training",
    titulo: "Treinar uma pausa de respiração",
    duracao: "3 min",
    formato: "audio",
    etiqueta: "Treinamento",
    intensidade: "baixa",
    cena: "registro",
  },
  {
    id: "training-checklist",
    categoria: "training",
    titulo: "Montar e conferir o checklist de saída",
    duracao: "4 min",
    formato: "checklist",
    etiqueta: "Treinamento",
    cena: "conteudo",
  },
  {
    id: "training-plano-b",
    categoria: "training",
    titulo: "Ensaiar o plano alternativo",
    duracao: "5 min",
    formato: "pratica",
    etiqueta: "Treinamento",
    cena: "alternativa",
  },
  {
    id: "training-saida",
    categoria: "training",
    titulo: "Ensaiar a saída antes do fim",
    duracao: "3 min",
    formato: "pratica",
    etiqueta: "Treinamento",
    cena: "etapa",
  },
];

export const monitoramentos: MonitoringPreference[] = [
  {
    id: "monitoring-silencioso",
    categoria: "monitoring",
    titulo: "Sem avisos durante",
    descricao: "Eu abro quando quiser.",
    etiqueta: "Monitoramento",
    intensidade: "baixa",
    cena: "perfil",
  },
  {
    id: "monitoring-etapa",
    categoria: "monitoring",
    titulo: "Um aviso discreto por etapa",
    etiqueta: "Monitoramento",
    intensidade: "baixa",
    cena: "etapa",
  },
  {
    id: "monitoring-pausa",
    categoria: "monitoring",
    titulo: "Lembrete de pausa",
    etiqueta: "Monitoramento",
    cena: "registro",
  },
  {
    id: "monitoring-alguem",
    categoria: "monitoring",
    titulo: "Alguém de confiança acompanha o trajeto",
    descricao: "Link temporário, que você encerra quando quiser.",
    etiqueta: "Monitoramento",
    cena: "alternativa",
    detalhes: "Nesta versão demonstrativa, o link é simulado e nada sai do aparelho.",
  },
  {
    id: "monitoring-checkin",
    categoria: "monitoring",
    titulo: "Eu marco cada etapa quando terminar",
    etiqueta: "Monitoramento",
    cena: "conteudo",
  },
  {
    id: "monitoring-saida",
    categoria: "monitoring",
    titulo: "Botão de sair a qualquer momento",
    etiqueta: "Monitoramento",
    cena: "alternativa",
  },
];

export const formatosDeFeedback: FeedbackFormat[] = [
  {
    id: "feedback-uma-palavra",
    categoria: "feedback",
    titulo: "Uma palavra sobre como foi",
    etiqueta: "Feedback",
    formato: "leitura",
    cena: "registro",
  },
  {
    id: "feedback-audio",
    categoria: "feedback",
    titulo: "Um áudio curto para mim mesmo",
    etiqueta: "Feedback",
    formato: "audio",
    cena: "registro",
  },
  {
    id: "feedback-checklist",
    categoria: "feedback",
    titulo: "Marcar o que funcionou",
    etiqueta: "Feedback",
    formato: "checklist",
    cena: "conteudo",
  },
  {
    id: "feedback-texto",
    categoria: "feedback",
    titulo: "Escrever livremente",
    etiqueta: "Feedback",
    formato: "leitura",
    cena: "registro",
  },
  {
    id: "feedback-nada",
    categoria: "feedback",
    titulo: "Não registrar nada desta vez",
    descricao: "Também é uma escolha válida.",
    etiqueta: "Feedback",
    cena: "perfil",
  },
];

export const catalogoDeMatch = {
  situation: situacoesDeMatch,
  need: necessidades,
  barrier: barreiras,
  strategy: estrategias,
  information: informacoes,
  training: treinamentos,
  monitoring: monitoramentos,
  feedback: formatosDeFeedback,
};
