/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VivaIndexRouteImport } from './routes/_viva.index'
import { Route as VivaCompartilharRouteImport } from './routes/_viva.compartilhar'
import { Route as VivaDocumentacaoRouteImport } from './routes/_viva.documentacao'
import { Route as VivaFavoritosRouteImport } from './routes/_viva.favoritos'
import { Route as VivaMeuPercursoRouteImport } from './routes/_viva.meu-percurso'
import { Route as VivaMinhaExperienciaRouteImport } from './routes/_viva.minha-experiencia'
import { Route as VivaPerfilRouteImport } from './routes/_viva.perfil'
import { Route as VivaSeusDadosRouteImport } from './routes/_viva.seus-dados'
import { Route as VivaSobreRouteImport } from './routes/_viva.sobre'
import { Route as AcompanharTokenRouteImport } from './routes/acompanhar.$token'
import { Route as DocumentosSlugRouteImport } from './routes/documentos.$slug'
import { Route as VivaBibliotecaIndexRouteImport } from './routes/_viva.biblioteca.index'
import { Route as VivaBibliotecaConteudoIdRouteImport } from './routes/_viva.biblioteca.$conteudoId'
import { Route as VivaBibliotecaMinhaRouteImport } from './routes/_viva.biblioteca.minha'
import { Route as VivaBibliotecaReflexoesRouteImport } from './routes/_viva.biblioteca.reflexoes'
import { Route as VivaPercursoIdRouteImport } from './routes/_viva.percurso.$id'

const VivaIndexRoute = VivaIndexRouteImport.update({
  id: '/_viva/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaCompartilharRoute = VivaCompartilharRouteImport.update({
  id: '/_viva/compartilhar',
  path: '/compartilhar',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaDocumentacaoRoute = VivaDocumentacaoRouteImport.update({
  id: '/_viva/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaFavoritosRoute = VivaFavoritosRouteImport.update({
  id: '/_viva/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaMeuPercursoRoute = VivaMeuPercursoRouteImport.update({
  id: '/_viva/meu-percurso',
  path: '/meu-percurso',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaMinhaExperienciaRoute = VivaMinhaExperienciaRouteImport.update({
  id: '/_viva/minha-experiencia',
  path: '/minha-experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaPerfilRoute = VivaPerfilRouteImport.update({
  id: '/_viva/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaSeusDadosRoute = VivaSeusDadosRouteImport.update({
  id: '/_viva/seus-dados',
  path: '/seus-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaSobreRoute = VivaSobreRouteImport.update({
  id: '/_viva/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharTokenRoute = AcompanharTokenRouteImport.update({
  id: '/acompanhar/$token',
  path: '/acompanhar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosSlugRoute = DocumentosSlugRouteImport.update({
  id: '/documentos/$slug',
  path: '/documentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaBibliotecaIndexRoute = VivaBibliotecaIndexRouteImport.update({
  id: '/_viva/biblioteca/',
  path: '/biblioteca/',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaBibliotecaConteudoIdRoute =
  VivaBibliotecaConteudoIdRouteImport.update({
    id: '/_viva/biblioteca/$conteudoId',
    path: '/biblioteca/$conteudoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const VivaBibliotecaMinhaRoute = VivaBibliotecaMinhaRouteImport.update({
  id: '/_viva/biblioteca/minha',
  path: '/biblioteca/minha',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaBibliotecaReflexoesRoute = VivaBibliotecaReflexoesRouteImport.update({
  id: '/_viva/biblioteca/reflexoes',
  path: '/biblioteca/reflexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const VivaPercursoIdRoute = VivaPercursoIdRouteImport.update({
  id: '/_viva/percurso/$id',
  path: '/percurso/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/compartilhar': typeof VivaCompartilharRoute
  '/documentacao': typeof VivaDocumentacaoRoute
  '/favoritos': typeof VivaFavoritosRoute
  '/meu-percurso': typeof VivaMeuPercursoRoute
  '/minha-experiencia': typeof VivaMinhaExperienciaRoute
  '/perfil': typeof VivaPerfilRoute
  '/seus-dados': typeof VivaSeusDadosRoute
  '/sobre': typeof VivaSobreRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/documentos/$slug': typeof DocumentosSlugRoute
  '/': typeof VivaIndexRoute
  '/biblioteca/$conteudoId': typeof VivaBibliotecaConteudoIdRoute
  '/biblioteca/minha': typeof VivaBibliotecaMinhaRoute
  '/biblioteca/reflexoes': typeof VivaBibliotecaReflexoesRoute
  '/percurso/$id': typeof VivaPercursoIdRoute
  '/biblioteca/': typeof VivaBibliotecaIndexRoute
}
export interface FileRoutesByTo {
  '/compartilhar': typeof VivaCompartilharRoute
  '/documentacao': typeof VivaDocumentacaoRoute
  '/favoritos': typeof VivaFavoritosRoute
  '/meu-percurso': typeof VivaMeuPercursoRoute
  '/minha-experiencia': typeof VivaMinhaExperienciaRoute
  '/perfil': typeof VivaPerfilRoute
  '/seus-dados': typeof VivaSeusDadosRoute
  '/sobre': typeof VivaSobreRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/documentos/$slug': typeof DocumentosSlugRoute
  '/': typeof VivaIndexRoute
  '/biblioteca/$conteudoId': typeof VivaBibliotecaConteudoIdRoute
  '/biblioteca/minha': typeof VivaBibliotecaMinhaRoute
  '/biblioteca/reflexoes': typeof VivaBibliotecaReflexoesRoute
  '/percurso/$id': typeof VivaPercursoIdRoute
  '/biblioteca': typeof VivaBibliotecaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_viva/compartilhar': typeof VivaCompartilharRoute
  '/_viva/documentacao': typeof VivaDocumentacaoRoute
  '/_viva/favoritos': typeof VivaFavoritosRoute
  '/_viva/meu-percurso': typeof VivaMeuPercursoRoute
  '/_viva/minha-experiencia': typeof VivaMinhaExperienciaRoute
  '/_viva/perfil': typeof VivaPerfilRoute
  '/_viva/seus-dados': typeof VivaSeusDadosRoute
  '/_viva/sobre': typeof VivaSobreRoute
  '/acompanhar/$token': typeof AcompanharTokenRoute
  '/documentos/$slug': typeof DocumentosSlugRoute
  '/_viva/': typeof VivaIndexRoute
  '/_viva/biblioteca/$conteudoId': typeof VivaBibliotecaConteudoIdRoute
  '/_viva/biblioteca/minha': typeof VivaBibliotecaMinhaRoute
  '/_viva/biblioteca/reflexoes': typeof VivaBibliotecaReflexoesRoute
  '/_viva/percurso/$id': typeof VivaPercursoIdRoute
  '/_viva/biblioteca/': typeof VivaBibliotecaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/compartilhar'
    | '/documentacao'
    | '/favoritos'
    | '/meu-percurso'
    | '/minha-experiencia'
    | '/perfil'
    | '/seus-dados'
    | '/sobre'
    | '/acompanhar/$token'
    | '/documentos/$slug'
    | '/'
    | '/biblioteca/$conteudoId'
    | '/biblioteca/minha'
    | '/biblioteca/reflexoes'
    | '/percurso/$id'
    | '/biblioteca/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/compartilhar'
    | '/documentacao'
    | '/favoritos'
    | '/meu-percurso'
    | '/minha-experiencia'
    | '/perfil'
    | '/seus-dados'
    | '/sobre'
    | '/acompanhar/$token'
    | '/documentos/$slug'
    | '/'
    | '/biblioteca/$conteudoId'
    | '/biblioteca/minha'
    | '/biblioteca/reflexoes'
    | '/percurso/$id'
    | '/biblioteca'
  id:
    | '__root__'
    | '/_viva/compartilhar'
    | '/_viva/documentacao'
    | '/_viva/favoritos'
    | '/_viva/meu-percurso'
    | '/_viva/minha-experiencia'
    | '/_viva/perfil'
    | '/_viva/seus-dados'
    | '/_viva/sobre'
    | '/acompanhar/$token'
    | '/documentos/$slug'
    | '/_viva/'
    | '/_viva/biblioteca/$conteudoId'
    | '/_viva/biblioteca/minha'
    | '/_viva/biblioteca/reflexoes'
    | '/_viva/percurso/$id'
    | '/_viva/biblioteca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VivaCompartilharRoute: typeof VivaCompartilharRoute
  VivaDocumentacaoRoute: typeof VivaDocumentacaoRoute
  VivaFavoritosRoute: typeof VivaFavoritosRoute
  VivaMeuPercursoRoute: typeof VivaMeuPercursoRoute
  VivaMinhaExperienciaRoute: typeof VivaMinhaExperienciaRoute
  VivaPerfilRoute: typeof VivaPerfilRoute
  VivaSeusDadosRoute: typeof VivaSeusDadosRoute
  VivaSobreRoute: typeof VivaSobreRoute
  AcompanharTokenRoute: typeof AcompanharTokenRoute
  DocumentosSlugRoute: typeof DocumentosSlugRoute
  VivaIndexRoute: typeof VivaIndexRoute
  VivaBibliotecaConteudoIdRoute: typeof VivaBibliotecaConteudoIdRoute
  VivaBibliotecaMinhaRoute: typeof VivaBibliotecaMinhaRoute
  VivaBibliotecaReflexoesRoute: typeof VivaBibliotecaReflexoesRoute
  VivaPercursoIdRoute: typeof VivaPercursoIdRoute
  VivaBibliotecaIndexRoute: typeof VivaBibliotecaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_viva/': {
      id: '/_viva/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof VivaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/compartilhar': {
      id: '/_viva/compartilhar'
      path: '/compartilhar'
      fullPath: '/compartilhar'
      preLoaderRoute: typeof VivaCompartilharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/documentacao': {
      id: '/_viva/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof VivaDocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/favoritos': {
      id: '/_viva/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof VivaFavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/meu-percurso': {
      id: '/_viva/meu-percurso'
      path: '/meu-percurso'
      fullPath: '/meu-percurso'
      preLoaderRoute: typeof VivaMeuPercursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/minha-experiencia': {
      id: '/_viva/minha-experiencia'
      path: '/minha-experiencia'
      fullPath: '/minha-experiencia'
      preLoaderRoute: typeof VivaMinhaExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/perfil': {
      id: '/_viva/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof VivaPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/seus-dados': {
      id: '/_viva/seus-dados'
      path: '/seus-dados'
      fullPath: '/seus-dados'
      preLoaderRoute: typeof VivaSeusDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/sobre': {
      id: '/_viva/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof VivaSobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/$token': {
      id: '/acompanhar/$token'
      path: '/acompanhar/$token'
      fullPath: '/acompanhar/$token'
      preLoaderRoute: typeof AcompanharTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos/$slug': {
      id: '/documentos/$slug'
      path: '/documentos/$slug'
      fullPath: '/documentos/$slug'
      preLoaderRoute: typeof DocumentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/biblioteca/': {
      id: '/_viva/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof VivaBibliotecaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/biblioteca/$conteudoId': {
      id: '/_viva/biblioteca/$conteudoId'
      path: '/biblioteca/$conteudoId'
      fullPath: '/biblioteca/$conteudoId'
      preLoaderRoute: typeof VivaBibliotecaConteudoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/biblioteca/minha': {
      id: '/_viva/biblioteca/minha'
      path: '/biblioteca/minha'
      fullPath: '/biblioteca/minha'
      preLoaderRoute: typeof VivaBibliotecaMinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/biblioteca/reflexoes': {
      id: '/_viva/biblioteca/reflexoes'
      path: '/biblioteca/reflexoes'
      fullPath: '/biblioteca/reflexoes'
      preLoaderRoute: typeof VivaBibliotecaReflexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_viva/percurso/$id': {
      id: '/_viva/percurso/$id'
      path: '/percurso/$id'
      fullPath: '/percurso/$id'
      preLoaderRoute: typeof VivaPercursoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  VivaCompartilharRoute: VivaCompartilharRoute,
  VivaDocumentacaoRoute: VivaDocumentacaoRoute,
  VivaFavoritosRoute: VivaFavoritosRoute,
  VivaMeuPercursoRoute: VivaMeuPercursoRoute,
  VivaMinhaExperienciaRoute: VivaMinhaExperienciaRoute,
  VivaPerfilRoute: VivaPerfilRoute,
  VivaSeusDadosRoute: VivaSeusDadosRoute,
  VivaSobreRoute: VivaSobreRoute,
  AcompanharTokenRoute: AcompanharTokenRoute,
  DocumentosSlugRoute: DocumentosSlugRoute,
  VivaIndexRoute: VivaIndexRoute,
  VivaBibliotecaConteudoIdRoute: VivaBibliotecaConteudoIdRoute,
  VivaBibliotecaMinhaRoute: VivaBibliotecaMinhaRoute,
  VivaBibliotecaReflexoesRoute: VivaBibliotecaReflexoesRoute,
  VivaPercursoIdRoute: VivaPercursoIdRoute,
  VivaBibliotecaIndexRoute: VivaBibliotecaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
