/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PercursoRouteImport } from './routes/_percurso'
import { Route as PercursoBarreirasRouteImport } from './routes/_percurso.barreiras'
import { Route as PercursoContextoRouteImport } from './routes/_percurso.contexto'
import { Route as PercursoEstrategiasRouteImport } from './routes/_percurso.estrategias'
import { Route as PercursoHabilidadesRouteImport } from './routes/_percurso.habilidades'
import { Route as PercursoObjetivoRouteImport } from './routes/_percurso.objetivo'
import { Route as PercursoOpcoesRouteImport } from './routes/_percurso.opcoes'
import { Route as PercursoPerfilRouteImport } from './routes/_percurso.perfil'
import { Route as PercursoPreparacaoRouteImport } from './routes/_percurso.preparacao'
import { Route as PercursoSistemaRouteImport } from './routes/_percurso.sistema'
import { Route as DocumentosSlugRouteImport } from './routes/documentos.$slug'
import { Route as PercursoBibliotecaIndexRouteImport } from './routes/_percurso.biblioteca.index'
import { Route as PercursoBibliotecaConteudoIdRouteImport } from './routes/_percurso.biblioteca.$conteudoId'
import { Route as PercursoEstrategiasAdaptarEstrategiaIdRouteImport } from './routes/_percurso.estrategias.adaptar.$estrategiaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PercursoRoute = PercursoRouteImport.update({
  id: '/_percurso',
  getParentRoute: () => rootRouteImport,
} as any)
const PercursoBarreirasRoute = PercursoBarreirasRouteImport.update({
  id: '/barreiras',
  path: '/barreiras',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoContextoRoute = PercursoContextoRouteImport.update({
  id: '/contexto',
  path: '/contexto',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoEstrategiasRoute = PercursoEstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoHabilidadesRoute = PercursoHabilidadesRouteImport.update({
  id: '/habilidades',
  path: '/habilidades',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoObjetivoRoute = PercursoObjetivoRouteImport.update({
  id: '/objetivo',
  path: '/objetivo',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoOpcoesRoute = PercursoOpcoesRouteImport.update({
  id: '/opcoes',
  path: '/opcoes',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoPerfilRoute = PercursoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoPreparacaoRoute = PercursoPreparacaoRouteImport.update({
  id: '/preparacao',
  path: '/preparacao',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoSistemaRoute = PercursoSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => PercursoRoute,
} as any)
const DocumentosSlugRoute = DocumentosSlugRouteImport.update({
  id: '/documentos/$slug',
  path: '/documentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PercursoBibliotecaIndexRoute = PercursoBibliotecaIndexRouteImport.update({
  id: '/biblioteca/',
  path: '/biblioteca/',
  getParentRoute: () => PercursoRoute,
} as any)
const PercursoBibliotecaConteudoIdRoute =
  PercursoBibliotecaConteudoIdRouteImport.update({
    id: '/biblioteca/$conteudoId',
    path: '/biblioteca/$conteudoId',
    getParentRoute: () => PercursoRoute,
  } as any)
const PercursoEstrategiasAdaptarEstrategiaIdRoute =
  PercursoEstrategiasAdaptarEstrategiaIdRouteImport.update({
    id: '/adaptar/$estrategiaId',
    path: '/adaptar/$estrategiaId',
    getParentRoute: () => PercursoEstrategiasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barreiras': typeof PercursoBarreirasRoute
  '/contexto': typeof PercursoContextoRoute
  '/estrategias': typeof PercursoEstrategiasRouteWithChildren
  '/habilidades': typeof PercursoHabilidadesRoute
  '/objetivo': typeof PercursoObjetivoRoute
  '/opcoes': typeof PercursoOpcoesRoute
  '/perfil': typeof PercursoPerfilRoute
  '/preparacao': typeof PercursoPreparacaoRoute
  '/sistema': typeof PercursoSistemaRoute
  '/documentos/$slug': typeof DocumentosSlugRoute
  '/biblioteca/$conteudoId': typeof PercursoBibliotecaConteudoIdRoute
  '/biblioteca/': typeof PercursoBibliotecaIndexRoute
  '/estrategias/adaptar/$estrategiaId': typeof PercursoEstrategiasAdaptarEstrategiaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barreiras': typeof PercursoBarreirasRoute
  '/contexto': typeof PercursoContextoRoute
  '/estrategias': typeof PercursoEstrategiasRouteWithChildren
  '/habilidades': typeof PercursoHabilidadesRoute
  '/objetivo': typeof PercursoObjetivoRoute
  '/opcoes': typeof PercursoOpcoesRoute
  '/perfil': typeof PercursoPerfilRoute
  '/preparacao': typeof PercursoPreparacaoRoute
  '/sistema': typeof PercursoSistemaRoute
  '/documentos/$slug': typeof DocumentosSlugRoute
  '/biblioteca/$conteudoId': typeof PercursoBibliotecaConteudoIdRoute
  '/biblioteca': typeof PercursoBibliotecaIndexRoute
  '/estrategias/adaptar/$estrategiaId': typeof PercursoEstrategiasAdaptarEstrategiaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_percurso': typeof PercursoRouteWithChildren
  '/_percurso/barreiras': typeof PercursoBarreirasRoute
  '/_percurso/contexto': typeof PercursoContextoRoute
  '/_percurso/estrategias': typeof PercursoEstrategiasRouteWithChildren
  '/_percurso/habilidades': typeof PercursoHabilidadesRoute
  '/_percurso/objetivo': typeof PercursoObjetivoRoute
  '/_percurso/opcoes': typeof PercursoOpcoesRoute
  '/_percurso/perfil': typeof PercursoPerfilRoute
  '/_percurso/preparacao': typeof PercursoPreparacaoRoute
  '/_percurso/sistema': typeof PercursoSistemaRoute
  '/documentos/$slug': typeof DocumentosSlugRoute
  '/_percurso/biblioteca/$conteudoId': typeof PercursoBibliotecaConteudoIdRoute
  '/_percurso/biblioteca/': typeof PercursoBibliotecaIndexRoute
  '/_percurso/estrategias/adaptar/$estrategiaId': typeof PercursoEstrategiasAdaptarEstrategiaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barreiras'
    | '/contexto'
    | '/estrategias'
    | '/habilidades'
    | '/objetivo'
    | '/opcoes'
    | '/perfil'
    | '/preparacao'
    | '/sistema'
    | '/documentos/$slug'
    | '/biblioteca/$conteudoId'
    | '/biblioteca/'
    | '/estrategias/adaptar/$estrategiaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barreiras'
    | '/contexto'
    | '/estrategias'
    | '/habilidades'
    | '/objetivo'
    | '/opcoes'
    | '/perfil'
    | '/preparacao'
    | '/sistema'
    | '/documentos/$slug'
    | '/biblioteca/$conteudoId'
    | '/biblioteca'
    | '/estrategias/adaptar/$estrategiaId'
  id:
    | '__root__'
    | '/'
    | '/_percurso'
    | '/_percurso/barreiras'
    | '/_percurso/contexto'
    | '/_percurso/estrategias'
    | '/_percurso/habilidades'
    | '/_percurso/objetivo'
    | '/_percurso/opcoes'
    | '/_percurso/perfil'
    | '/_percurso/preparacao'
    | '/_percurso/sistema'
    | '/documentos/$slug'
    | '/_percurso/biblioteca/$conteudoId'
    | '/_percurso/biblioteca/'
    | '/_percurso/estrategias/adaptar/$estrategiaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PercursoRoute: typeof PercursoRouteWithChildren
  DocumentosSlugRoute: typeof DocumentosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_percurso': {
      id: '/_percurso'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PercursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_percurso/barreiras': {
      id: '/_percurso/barreiras'
      path: '/barreiras'
      fullPath: '/barreiras'
      preLoaderRoute: typeof PercursoBarreirasRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/contexto': {
      id: '/_percurso/contexto'
      path: '/contexto'
      fullPath: '/contexto'
      preLoaderRoute: typeof PercursoContextoRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/estrategias': {
      id: '/_percurso/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof PercursoEstrategiasRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/habilidades': {
      id: '/_percurso/habilidades'
      path: '/habilidades'
      fullPath: '/habilidades'
      preLoaderRoute: typeof PercursoHabilidadesRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/objetivo': {
      id: '/_percurso/objetivo'
      path: '/objetivo'
      fullPath: '/objetivo'
      preLoaderRoute: typeof PercursoObjetivoRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/opcoes': {
      id: '/_percurso/opcoes'
      path: '/opcoes'
      fullPath: '/opcoes'
      preLoaderRoute: typeof PercursoOpcoesRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/perfil': {
      id: '/_percurso/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PercursoPerfilRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/preparacao': {
      id: '/_percurso/preparacao'
      path: '/preparacao'
      fullPath: '/preparacao'
      preLoaderRoute: typeof PercursoPreparacaoRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/sistema': {
      id: '/_percurso/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof PercursoSistemaRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/documentos/$slug': {
      id: '/documentos/$slug'
      path: '/documentos/$slug'
      fullPath: '/documentos/$slug'
      preLoaderRoute: typeof DocumentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_percurso/biblioteca/': {
      id: '/_percurso/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof PercursoBibliotecaIndexRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/biblioteca/$conteudoId': {
      id: '/_percurso/biblioteca/$conteudoId'
      path: '/biblioteca/$conteudoId'
      fullPath: '/biblioteca/$conteudoId'
      preLoaderRoute: typeof PercursoBibliotecaConteudoIdRouteImport
      parentRoute: typeof PercursoRoute
    }
    '/_percurso/estrategias/adaptar/$estrategiaId': {
      id: '/_percurso/estrategias/adaptar/$estrategiaId'
      path: '/adaptar/$estrategiaId'
      fullPath: '/estrategias/adaptar/$estrategiaId'
      preLoaderRoute: typeof PercursoEstrategiasAdaptarEstrategiaIdRouteImport
      parentRoute: typeof PercursoEstrategiasRoute
    }
  }
}

interface PercursoEstrategiasRouteChildren {
  PercursoEstrategiasAdaptarEstrategiaIdRoute: typeof PercursoEstrategiasAdaptarEstrategiaIdRoute
}

const PercursoEstrategiasRouteChildren: PercursoEstrategiasRouteChildren = {
  PercursoEstrategiasAdaptarEstrategiaIdRoute:
    PercursoEstrategiasAdaptarEstrategiaIdRoute,
}

const PercursoEstrategiasRouteWithChildren =
  PercursoEstrategiasRoute._addFileChildren(PercursoEstrategiasRouteChildren)

interface PercursoRouteChildren {
  PercursoBarreirasRoute: typeof PercursoBarreirasRoute
  PercursoContextoRoute: typeof PercursoContextoRoute
  PercursoEstrategiasRoute: typeof PercursoEstrategiasRouteWithChildren
  PercursoHabilidadesRoute: typeof PercursoHabilidadesRoute
  PercursoObjetivoRoute: typeof PercursoObjetivoRoute
  PercursoOpcoesRoute: typeof PercursoOpcoesRoute
  PercursoPerfilRoute: typeof PercursoPerfilRoute
  PercursoPreparacaoRoute: typeof PercursoPreparacaoRoute
  PercursoSistemaRoute: typeof PercursoSistemaRoute
  PercursoBibliotecaConteudoIdRoute: typeof PercursoBibliotecaConteudoIdRoute
  PercursoBibliotecaIndexRoute: typeof PercursoBibliotecaIndexRoute
}

const PercursoRouteChildren: PercursoRouteChildren = {
  PercursoBarreirasRoute: PercursoBarreirasRoute,
  PercursoContextoRoute: PercursoContextoRoute,
  PercursoEstrategiasRoute: PercursoEstrategiasRouteWithChildren,
  PercursoHabilidadesRoute: PercursoHabilidadesRoute,
  PercursoObjetivoRoute: PercursoObjetivoRoute,
  PercursoOpcoesRoute: PercursoOpcoesRoute,
  PercursoPerfilRoute: PercursoPerfilRoute,
  PercursoPreparacaoRoute: PercursoPreparacaoRoute,
  PercursoSistemaRoute: PercursoSistemaRoute,
  PercursoBibliotecaConteudoIdRoute: PercursoBibliotecaConteudoIdRoute,
  PercursoBibliotecaIndexRoute: PercursoBibliotecaIndexRoute,
}

const PercursoRouteWithChildren = PercursoRoute._addFileChildren(
  PercursoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PercursoRoute: PercursoRouteWithChildren,
  DocumentosSlugRoute: DocumentosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
